Add automatic host attachment
tcpcloud/salt-formula-freeipa pull request #2
Opened 2017-05-26 08:02 UTC by jdshewey

The current installer only works if a bulk password has already been created. These changes allow an endpoint to use the JSON interface in FreeIPA to register on-the-fly if provided a kerberos principal. I have tested and confirmed this code is working for me.

2017-05-26 08:02 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2017-06-02 06:35 UTC, fpytloun requested changes
Thank you for this change, I like it :-)
Please see my comments above for a few adjustments.

2017-06-02 06:35 UTC, fpytloun commented on README.rst
> +To automatically register the client with FreeIPA, you will need to first create a Kerberos principal. Start by creating a service account in FreeIPA. You may wish to restrict that users permissions
Please wrap lines here

2017-06-02 06:35 UTC, fpytloun commented on README.rst
> +This will allow your client to use FreeIPA's JSON interface to create a host entry with a One Time Password and then register to the FreeIPA server. For security purposes, the kerberos principl will
Typo principl -> principal + wrap lines

2017-06-02 06:35 UTC, fpytloun commented on README.rst
> +Additionally, the openssh formula (see https://github.com/salt-formulas/salt-formula-openssh) is needed and is a dependancy for this formula. Configure it thusly:
dependancy -> dependency

2017-06-02 06:35 UTC, fpytloun commented on freeipa/client/init.sls
> +{%- if pillar.freeipa.client.install_principal is defined %}
Refer `client` instead of pillar as it passes defaults substitution through map.jinja.

2017-06-02 06:35 UTC, fpytloun commented on freeipa/client/init.sls
> +push_principal:
It's good to prefix all resources with formula name (eg. freeipa_client_principal_file) to avoid conflict with other states' resources

2017-06-02 06:35 UTC, fpytloun commented on freeipa/client/init.sls
> +    - name: kinit {{ client.get("install_principal", {}).get("principal_user", "root") }}@{{ client.get("realm", "") }} -kt /tmp/salt-service.keytab
I think it's better to call kinit in commands where it's needed and kdestroy it when it's executed.

2017-06-02 06:35 UTC, fpytloun commented on freeipa/client/init.sls
> +        }' https://{{ client.get("server", {}) }}/ipa/json
There can be multiple servers configured. To provide transparent support for one vs many servers, you should use `ipa_servers` list that's provided by map.jinja and use first item in that list as a server (or implement fallbacks to others).
Also you are defaulting to empty dict which probably won't be any useful.

2017-06-02 06:35 UTC, fpytloun commented on freeipa/client/init.sls
> +cleanup_cookiejar:
IMO this should be cleaned immediately when it's not needed (so after curl call as a part of ipa_host_add state

2017-06-14 17:58 UTC, jdshewey commented on freeipa/client/init.sls
> +    - name: kinit {{ client.get("install_principal", {}).get("principal_user", "root") }}@{{ client.get("realm", "") }} -kt /tmp/salt-service.keytab
I'm not sure I understand - are you suggesting that this be done as kinit && examplecommand && kdestroy? As it is now, the principal only pushes out if IPA Client install does not report "IPA client is already configured on this system" in which case, it is assumed that a host needs to be created on the IPA server for which a kerberos ticket is required, so kinit is only called when needed and destroyed after we are done.

2017-06-18 07:07 UTC, jdshewey commented
OK, these changes have been applied. Did I resubmit this right? Do I need to do anything else?

2017-06-19 12:33 UTC, merged

2017-06-19 12:33 UTC, fpytloun commented
Thank you :)